'use client';
import { useState } from 'react';
import { ArrowDown, ArrowUpRight, Code2, MapPin, MousePointer2, PenTool } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';

const projects = [
  { name: 'Real Estate Agency', category: 'Development', number: '01', tag: 'NEXT.JS / TYPESCRIPT', description: 'A responsive property-listing experience with search, filters, and multiple languages.', url: 'https://github.com/mexx-0067/real-estate-agency-webapp', visual: 'estate', label: 'Explore the repository' },
  { name: 'Interface Explorations', category: 'Design', number: '02', tag: 'FIGMA / UI DESIGN', description: 'A collection of interface work, visual explorations, and prototypes.', url: 'https://www.figma.com/design/UeKp3K25D1D3bGn0eRUaY8/Tursunov-Mehroj', visual: 'design', label: 'Open Figma collection' },
  { name: 'RouteWise', category: 'Development', number: '03', tag: 'PYTHON / GRAPH ALGORITHMS', description: 'A command-line route planner comparing cheapest paths with fewest-hop routes. Built with AI assistance.', url: 'https://github.com/mexx-0067/routewise-cli', visual: 'routes', label: 'Explore the repository' },
  { name: 'Property Search API', category: 'Development', number: '04', tag: 'NODE.JS / REST API', description: 'Validated property search, stable sorting, pagination, and statistics over fictional listings. Built with AI assistance.', url: 'https://github.com/mexx-0067/property-search-api', visual: 'api', label: 'Explore the repository' },
];
const experience = [
  { role: 'Graphic Designer · UX/UI', company: 'Inovatsiyai Oyandasoz', location: 'Khujand', date: '2023 — 2024', details: 'Designed interfaces in Figma, created wireframes and interactive prototypes, and worked with developers to turn requirements into usable layouts.', more: 'Contributed design work to projects including Taxi Maxim, and refined interfaces through team reviews and feedback.' },
  { role: 'Customer Service Representative', company: 'LLC Tcell', location: 'Khujand', date: 'SEP 2021 — MAR 2024', details: 'Opened 30+ customer accounts daily, resolved service issues, and maintained client information.', more: 'Built communication and problem-solving skills by helping a diverse range of customers.' },
  { role: 'Seasonal Tour & Customer Service', company: 'Central Park', location: 'New York', date: 'DEC 2025', details: 'Provided guided tours during the Christmas season, managed high customer volume, and negotiated pricing.', more: 'Focused on guest comfort, safety, and clear communication in a fast-paced outdoor environment.' },
  { role: 'Volunteer & Coordinator', company: 'Tut Co-Working', location: 'Khujand', date: 'SEP 2019 — JUL 2020', details: 'Supported community initiatives and taught free English and introductory programming courses.', more: 'Coordinated volunteers and helped community members solve problems.' },
];

function ProjectVisual({ kind }: { kind: string }) {
  if (kind === 'routes') return <div className="route-study" aria-label="Diagram of a shortest path from Campus through Library and Market to Station"><svg viewBox="0 0 460 190" role="img"><title>Shortest-path graph study</title><path d="M45 95 L165 40 L295 40 L415 95 L295 150 L165 150 Z M45 95 H415" fill="none" stroke="#444c41" strokeWidth="2"/><path d="M45 95 L165 40 L295 40 L415 95" fill="none" stroke="currentColor" strokeWidth="3"/>{[[45,95],[165,40],[295,40],[415,95],[295,150],[165,150]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="9" fill={i<4?'currentColor':'#111711'} stroke="currentColor"/><text x={x} y={y+(i===1||i===2?-19:29)} textAnchor="middle" fill="#b5c6ae" fontSize="12">{['Campus','Library','Market','Station','Museum','Park'][i]}</text></g>)}</svg><span className="visual-caption">DIJKSTRA · MINIMUM TOTAL COST</span></div>;
  if (kind === 'api') return <div className="api-study"><span>GET /api/properties?city=Toronto</span><pre>{`{\n  "data": [ ... ],\n  "pagination": {\n    "page": 1, "total": 3\n  }\n}`}</pre><span className="response-badge">200 OK · JSON RESPONSE</span></div>;
  if (kind === 'design') return <div className="type-study"><span className="micro-label">FORM / FUNCTION / FEELING</span><strong>Aa<span>↔</span></strong><div className="type-rules"><span>Hierarchy</span><span>Rhythm</span><span>Clarity</span></div></div>;
  return <div className="estate-study"><span className="micro-label">PROPERTY DISCOVERY / INTERFACE STUDY</span><strong>Find a place.<br/>Make it yours.</strong><div className="filter-study"><span>Toronto</span><span>Condo</span><span>Search <ArrowUpRight size={14}/></span></div></div>;
}

function ProjectGrid({ filter }: { filter: string }) {
  return <div className="project-grid">{projects.filter(p=>filter==='All'||p.category===filter).map(p=><article className="project-card" key={p.name}><a href={p.url} target="_blank" rel="noreferrer" aria-label={`${p.name}: ${p.label}`}><div className={`project-visual ${p.visual}`}><ProjectVisual kind={p.visual}/></div><div className="project-title"><h3>{p.name}</h3><ArrowUpRight size={22}/></div></a><p className="project-tag">{p.number} / {p.tag}</p><p className="project-description">{p.description}</p></article>)}</div>;
}

export default function Home() {
  const [accent, setAccent] = useState('lime');
  return <div className={`portfolio accent-${accent}`}>
    <a className="skip" href="#main">Skip to content</a>
    <header className="topbar"><a className="wordmark" href="#main" aria-label="Mehroj Tursunov home">mt<span> /</span></a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#experience">Experience</a></nav><a className="contact-link" href="mailto:tursunovmehroj0067@gmail.com">Let’s talk <ArrowUpRight size={17}/></a></header>
    <main id="main">
      <section className="hero" aria-labelledby="intro"><div className="intro"><p className="eyebrow">MEHROJ TURSUNOV <span>/</span> PORTFOLIO 2026</p><h1 id="intro">Thoughtful<br/>design.<br/><em>Working code.</em></h1><p className="hero-copy">I’m a front-end developer and UI/UX designer in Toronto. I bring interfaces from the first wireframe to the final interaction.</p><div className="hero-actions"><a className="primary-link" href="#work">Explore my work <ArrowDown size={18}/></a><span className="location"><MapPin size={15}/> Toronto, ON</span></div></div>
        <div className="studio"><div className="studio-label"><span>THE INTERSECTION</span><span>01 — LIVE STUDY</span></div><Tabs defaultValue="design" className="studio-tabs"><TabsList className="view-switch" aria-label="Explore design and code"><TabsTrigger value="design"><PenTool size={15}/> Design</TabsTrigger><TabsTrigger value="code"><Code2 size={15}/> Code</TabsTrigger></TabsList><TabsContent value="design" className="specimen"><span className="micro-label">INTERFACE / PERSONAL IDENTITY</span><div className="monogram" aria-label="MT monogram">m<span>t</span>{['tl','tr','bl','br'].map(c=><i key={c} className={`handle ${c}`}/>)}</div><div className="specimen-footer"><div><strong>Mehroj Tursunov</strong><p>Developer. Designer. Problem solver.</p></div><MousePointer2 className="pointer" size={30}/></div></TabsContent><TabsContent value="code" className="code-specimen"><span className="micro-label">identity.tsx</span><pre><code>{`const mehroj = {\n  location: "Toronto, ON",\n  craft: ["UI / UX", "Front-end"],\n  tools: [\n    "TypeScript", "React",\n    "Next.js", "Figma"\n  ],\n  approach: "Design. Build. Refine."\n};\n\nexport default function Identity() {\n  return <Portfolio {...mehroj} />;\n}`}</code></pre><p>One perspective. Two ways to build it.</p></TabsContent></Tabs><div className="palette"><span>Make it your color</span><div role="group" aria-label="Portfolio accent color">{['lime','blue','orange'].map(color=><button key={color} type="button" className={`swatch ${color}`} aria-label={`${color} accent`} aria-pressed={accent===color} onClick={()=>setAccent(color)}/>)}</div></div></div>
      </section>
      <div className="craft-strip" aria-label="Core tools">{['FIGMA','REACT','TYPESCRIPT','NEXT.JS','PYTHON','C / C++'].map(t=><span key={t}>{t}</span>)}</div>
      <section id="work" className="section"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Ideas, made tangible.</h2></div><a className="text-link" href="https://github.com/mexx-0067" target="_blank" rel="noreferrer">All repositories <ArrowUpRight size={17}/></a></div><p className="section-intro">Web experiences, practical tools, and a growing collection of experiments.</p><Tabs defaultValue="All" className="work-tabs"><TabsList aria-label="Filter projects" className="project-filters">{['All','Development','Design'].map(f=><TabsTrigger key={f} value={f}>{f}</TabsTrigger>)}</TabsList>{['All','Development','Design'].map(f=><TabsContent key={f} value={f}><ProjectGrid filter={f}/></TabsContent>)}</Tabs></section>
      <section id="about" className="section about-section"><div><p className="eyebrow">02 / A LITTLE CONTEXT</p><h2>Curiosity is<br/>my common thread.</h2><p className="about-copy">From designing interfaces in Khujand to studying programming in Toronto, I’m interested in how things look, how they work, and how people use them.</p><p className="about-copy">My background brings together UI design, programming, teaching, and customer service. I enjoy moving between the visual details and the logic underneath.</p><div className="language-list"><span>Tajiki · Native</span><span>Russian · Native</span><span>English · Fluent</span><span>Farsi / Persian · Fluent</span></div></div><div className="toolbox"><p className="eyebrow">MY TOOLBOX</p><div><span>01 / INTERFACES</span><h3>Design with purpose.</h3><p>Figma · UI/UX · Wireframing · Prototyping</p></div><div><span>02 / DEVELOPMENT</span><h3>Build with structure.</h3><p>React · TypeScript · Next.js · HTML · CSS</p></div><div><span>03 / FOUNDATIONS</span><h3>Understand the logic.</h3><p>Python · C / C++ · Data structures · Algorithms</p></div></div></section>
      <section id="experience" className="section"><div className="section-heading"><div><p className="eyebrow">03 / EXPERIENCE</p><h2>People first. Always.</h2></div><button className="print-button" onClick={()=>window.print()}>Print résumé</button></div><div className="timeline">{experience.map(item=><article className="timeline-item" key={item.company}><p className="timeline-date">{item.date}</p><div><h3>{item.role}</h3><p className="company">{item.company} <span>/ {item.location}</span></p><p>{item.details}</p><details><summary>More about this role</summary><p>{item.more}</p></details></div></article>)}</div><div className="education"><p className="eyebrow">EDUCATION</p><div className="education-row"><h3>Seneca Polytechnic</h3><p>Computer Programming Diploma</p><span>Fall 2024 — Winter 2026</span></div><div className="education-row"><h3>IBT College, Toronto</h3><p>English as a Second Language</p><span>March — May 2024</span></div><div className="education-row"><h3>Lyceum of Polytechnic Institution</h3><p>High School Diploma · Khujand</p><span>September 2020 — July 2023</span></div><div className="education-row"><h3>Amid Private School</h3><p>High School · Khujand</p><span>September 2021 — May 2023</span></div></div></section>
      <section className="contact-section" id="contact"><p className="eyebrow">04 / WHAT’S NEXT?</p><h2>Let’s build<br/><em>something useful.</em></h2><a className="email-link" href="mailto:tursunovmehroj0067@gmail.com">tursunovmehroj0067@gmail.com <ArrowUpRight size={23}/></a><p>Development, design, or a good conversation.</p></section>
    </main><footer><span>© 2026 Mehroj Tursunov</span><a href="https://github.com/mexx-0067"><Code2 size={16}/> GitHub</a></footer>
  </div>;
}
